layout_spectrum: 1
typography_spectrum: 0.7150084
color:
  saturation: 0.7200674
  lightness: 0.4536256
  brandStrength: 0.4550956
  brandColors:
    - '#150F0B'
    - '#FFFFFF'
    - '#BDA353'
    - '#D8BE87'
    - '#CFCFC5'
  rhythmicContrast: 0.7740303
name: Maurie
